// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function numDaysInMonth(year, _) {
  Pervasives.print_int(year);
  Pervasives.print_newline(/* () */0);
  return year;
}

exports.numDaysInMonth = numDaysInMonth;
/* No side effect */
