// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


function timeDifference(_, _$1) {
  return /* () */0;
}

exports.timeDifference = timeDifference;
/* No side effect */
