// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Date$DateRe = require("./Date.bs.js");

function numDaysInMonthNoMonth(param) {
  return Date$DateRe.numDaysInMonth(2014, param);
}

var date0 = /* record */[
  /* year */2018,
  /* month : February */1,
  /* day */14
];

var date1 = /* record */[
  /* year */2017,
  /* month : November */10,
  /* day */11
];

exports.date0 = date0;
exports.date1 = date1;
exports.numDaysInMonthNoMonth = numDaysInMonthNoMonth;
/* No side effect */
