// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Print$DateRe = require("./Print.bs.js");

var date0 = /* record */[
  /* year */2018,
  /* month : February */1,
  /* monthIndex */1,
  /* day */20,
  /* hour */20
];

var date1 = /* record */[
  /* year */2017,
  /* month : November */10,
  /* monthIndex */10,
  /* day */20,
  /* hour */22
];

Print$DateRe.print_date(date0);

Print$DateRe.print_date(date1);

exports.date0 = date0;
exports.date1 = date1;
/*  Not a pure module */
