// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");

function index(m) {
  if (typeof m === "number") {
    switch (m) {
      case 0 : 
          return 0;
      case 1 : 
          return 2;
      case 2 : 
          return 3;
      case 3 : 
          return 4;
      case 4 : 
          return 5;
      case 5 : 
          return 6;
      case 6 : 
          return 7;
      case 7 : 
          return 8;
      case 8 : 
          return 9;
      case 9 : 
          return 10;
      case 10 : 
          return 11;
      
    }
  } else {
    return 1;
  }
}

function numDays(m) {
  if (typeof m === "number") {
    switch (m) {
      case 2 : 
      case 4 : 
      case 7 : 
      case 9 : 
          return 30;
      case 0 : 
      case 1 : 
      case 3 : 
      case 5 : 
      case 6 : 
      case 8 : 
      case 10 : 
          return 31;
      
    }
  } else {
    var match = m[0] % 4 === 0;
    if (match) {
      return 29;
    } else {
      return 28;
    }
  }
}

function toString(m) {
  if (typeof m === "number") {
    switch (m) {
      case 0 : 
          return "January";
      case 1 : 
          return "March";
      case 2 : 
          return "April";
      case 3 : 
          return "May";
      case 4 : 
          return "June";
      case 5 : 
          return "July";
      case 6 : 
          return "August";
      case 7 : 
          return "September";
      case 8 : 
          return "October";
      case 9 : 
          return "November";
      case 10 : 
          return "December";
      
    }
  } else {
    return "February";
  }
}

function months(index, year) {
  var months$1 = /* array */[
    /* January */0,
    /* February */[year],
    /* March */1,
    /* April */2,
    /* May */3,
    /* June */4,
    /* July */5,
    /* August */6,
    /* September */7,
    /* October */8,
    /* November */9,
    /* December */10
  ];
  return Caml_array.caml_array_get(months$1, index);
}

exports.index = index;
exports.numDays = numDays;
exports.toString = toString;
exports.months = months;
/* No side effect */
